# Generated by Django 3.2.8 on 2021-12-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_poster', '0005_alter_posterprofile_jobs_posted'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblistings',
            name='user',
        ),
        migrations.AddField(
            model_name='joblistings',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_poster.posterprofile'),
        ),
    ]
