# Generated by Django 3.2.8 on 2021-12-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_auto_20211206_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekerprofile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
