# Generated by Django 3.2.8 on 2021-12-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_auto_20211210_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
