# Generated by Django 3.2.8 on 2021-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_poster', '0002_alter_posterprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
