# Generated by Django 3.2.8 on 2021-12-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_poster', '0003_alter_posterprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterprofile',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
    ]
