# Generated by Django 3.2.8 on 2021-12-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_poster', '0004_posterprofile_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterprofile',
            name='jobs_posted',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
